services:
  app:
    build: .
    container_name: tokyn
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DB=/data/data.db
      - REDIS_ADDR=redis:6379
      - APP_ADDR=0.0.0.0:8080
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis_np
    ports:
      - "6379:6379"